(function($){
	$.fn.HDslide=function(settings){
		settings=jQuery.extend({
			"auto":true,//是否自动播放
			"autoTime":2500,
			"time":200

		},settings)
		$.fn.HDslide.show($(this),settings);
	};
	$.fn.HDslide.show=function($this,settings){
		/*定义变量：导航，鼠标放上去定时器，自动播放定时器*/
		var _slide_nav=$this.children('.slide-nav'),
			t='';
			t_i='';
			if(settings.auto){/*判断是否自动播放*/
				$.fn.HDslide.autoSlide(_slide_nav,$this,settings);
			}
			/*鼠标放上去*/
			$('li',_slide_nav).hover(function(){
				var _this=$(this);
				if(settings.auto){
					clearTimeout(t_i);/*自动播放时清除定时器*/
				}
				if(_this.is('.slide-nav-curr')==false){/*多少秒后执行，切换*/
					t=setTimeout(function(){/*隐藏所有的li，获取当前index：0，1，2，3*/
						$('.slide-list',$this).hide();
						/*动画效果透明度*/
						$('.slide-list',$this).eq(_this.index()).animate({"opacity":"show"});
						/*移除所有li下的class，然后在当前鼠标移上的li加上class*/
						$('li',_slide_nav).removeClass('slide-nav-curr');
						_this.addClass('slide-nav-curr');
					},settings.time);
				}
			},function(){
				/*清除鼠标放上的定时器*/
				t==''?null:clearTimeout(t);
				if(settings.auto){
					$.fn.HDslide.autoSlide(_slide_nav,$this,settings);
				}
			});
	}
	$.fn.HDslide.autoSlide=function(_slide_nav,$this,settings){
		/*获取所有li的个数*/
		var _slide_nums=_slide_nav.find('li').length,
			i=_slide_nav.find('.slide-nav-curr').index();
			t_i=setInterval(function(){
				i+=1;
				if(i==_slide_nums){
					i=0;
				}
				$('.slide-list',$this).hide();/*隐藏所有的li*/
				$('.slide-list',$this).eq(i).animate({"opacity":"show"});/*显示当前*/
				$('li',_slide_nav).removeClass('slide-nav-curr');
					_slide_nav.find('li:eq('+i+')').addClass('slide-nav-curr');
			},settings.autoTime);
		// alert(_slide_nums);
	}
})(jQuery)
